train:   # 训练参数
  multi_gpu: false  # 是否使用多GPU
  is_train: True  # 是否训练
  continue_train: false  # 是否接着上次训练
  gpu: 7  # 使用GPU序号
  batch_size: 8  # 批大小
  num_workers: 4  # 线程数
  seed: 1234  # 随机种子
  overlap: 0.75
  max_epochs: 300  # 最大训练轮数
  epoch_start: 0  # 起始训练轮数
  save_freq: 10  # 保存间隔
  val_freq: 30  # 验证间隔
  log_freq: 10  # 日志记录间隔
  model_name: ""

val:
  overlap: 0.5

path:
  save_dir: "./Result/Segment/"
  checkpoint_path: ""

data:   # 数据参数
  split_dir:  "/data1/weiyibo/NPC-MRI/Code/Pctch_model/Split/zhongshan2" # "/data1/weiyibo/NPC-MRI/Split/Resample_Register_NII_zhongshan2/"
  norm_mode: "global_norm"
  resize_image_shape: [36, 256, 256]
  patch_image_shape: [16, 256, 256]
  img_con_name: ["T1C_mask", "T2", "T1C_tumor"]
  sour_img_name: "T2"
  targ_img_name: "T2_mask"
  overlap: 0.1
  num_random_crops: 16

loss:
  lambda_bce: 1.0
  lambda_dice: 10.0

net: 
  spatial_dims: 3
  in_channels: 1
  out_channels: 1
  kernel_size: [3, 3, 3, 3]
  strides: [1, 2, 2, 2]
  upsample_kernel_size: [2, 2, 2]
  filters: [32, 64, 128, 256]
  dropout: 0.1
  norm_name: "batch"
  res_block: True

optim:  # 生成器优化器参数
  optimizer:
    name: "AdamW"
    params:
      lr: 0.001
  scheduler:
    name: "StepLR"
    params:
      step_size: 10
      gamma: 0.1